name: Build and Test

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: Admin97
          POSTGRES_DB: WebsiteForRentIntegration
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      working-directory: WebSiteSolution/
      
    - name: Build
      run: dotnet build --no-restore
      working-directory: WebSiteSolution/
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: WebSiteSolution/

    - name: Test with Coverage
      run: dotnet test --no-build --verbosity normal --logger trx --collect:"XPlat Code Coverage" /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=TestResults/coverage
      working-directory: WebSiteSolution/

    - name: Install ReportGenerator
      run: dotnet tool install --global dotnet-reportgenerator-globaltool
      working-directory: WebSiteSolution/

    - name: Generate Coverage Report
      run: reportgenerator -reports:"**/TestResults/*/coverage.cobertura.xml" -targetdir:coverage -reporttypes:HtmlInline,Cobertura,MarkdownSummary
      working-directory: WebSiteSolution/

    - name: Upload Coverage Report as Artifact
      uses: actions/upload-artifact@v4
      with:
          name: code-coverage-report
          path: coverage

    - name: Publish Code Coverage Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
          filename: "coverage/coverage.cobertura.xml"
          badge: true
          fail_below_min: false
          format: markdown
          hide_branch_rate: false
          hide_complexity: false
          indicators: true
          output: both
          thresholds: '80'

    - name: Add Coverage PR Comment
      if: github.event_name == 'pull_request'
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        recreate: true
        path: coverage/Summary.md
        header: code-coverage

    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: "**/TestResults/**/*.trx"

    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        trx_files: "**/TestResults/**/*.trx"
